### ISSUE TITLE
Possibility to include some files from an other server

### ISSUE THREAD

**Issue by spruce** [gdub22/ember-cli-inline-content#3]
Link over from stefanpenner/ember-cli#2244
```javascript
inlineContent: {
    'google-analytics' : {'ext/google-analytics.js', env: ['test', 'prod']},
    'bar' : {'http://google.de/some-place/analytics.js', env: ['all']}, 
    'fast-style' : 'ext/red.css' // don't break old syntax
  }
```

**Comment by knownasilya** [comment]
@gdub22 would love urls being supported, without having to write HTML markup, with the ability to add query params.

```js
inlineContent: {
  url: '//maps.googleapis.com/maps/api/js',
  params: {
    v: '3.exp',
    libraries: ['drawing', 'geometry'].join(',')
  }
}
```

**Comment by gdub22** [comment]
@knownasilya are you just wanting the output to be `<script src="http://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing,geometry"></script>`?  Or do you want the addon to download that src and inline it's contents in script tags? The latter is what this issue is referencing, and has been hard to solve due to caching, invalidating, offline, etc.

**Comment by knownasilya** [comment]
The former.

**Comment by gdub22** [comment]
@knownasilya cool, should be possible.  If you want to open a separate issue we can discuss the right api for that feature.

**Comment by gdub22** [comment]
Closing this due to confusion of what this issue seeks to achieve.  Feel free to open separate issues.
